import "server-only"

import { Counter, Histogram, register } from "prom-client"

export const LOCATION_SEARCH_OPERATION = {
  SEARCH: "search",
  SEARCH_BY_DOCUMENT: "search_by_document",
  DETAIL: "detail",
} as const

export type LocationSearchOperation =
  (typeof LOCATION_SEARCH_OPERATION)[keyof typeof LOCATION_SEARCH_OPERATION]

export const LOCATION_SEARCH_RESULT = {
  FOUND: "found",
  EMPTY: "empty",
  ERROR: "error",
} as const

export type LocationSearchResult =
  (typeof LOCATION_SEARCH_RESULT)[keyof typeof LOCATION_SEARCH_RESULT]

export const REPORT_TYPE = {
  DECEASED: "deceased",
  BURIALS_BY_PERIOD: "burials_by_period",
  SPACE_OCCUPATION: "space_occupation",
  SPACE_STATUS: "space_status",
} as const

export type ReportType =
  (typeof REPORT_TYPE)[keyof typeof REPORT_TYPE]

export const REPORT_RESULT = {
  FOUND: "found",
  EMPTY: "empty",
  ERROR: "error",
} as const

export type ReportResult =
  (typeof REPORT_RESULT)[keyof typeof REPORT_RESULT]

interface LocationSearchObservation {
  operation: LocationSearchOperation
  result: LocationSearchResult
  durationMs: number
  userId?: string
  resultCount?: number
}

interface ReportObservation {
  type: ReportType
  result: ReportResult
  durationMs: number
  userId?: string
  resultCount?: number
}

const LOCATION_SEARCH_TOTAL_NAME = "jaziggo_location_search_total"
const LOCATION_SEARCH_DURATION_NAME =
  "jaziggo_location_search_duration_seconds"
const REPORTS_GENERATED_TOTAL_NAME = "jaziggo_reports_generated_total"
const REPORT_GENERATION_DURATION_NAME =
  "jaziggo_report_generation_duration_seconds"
const DISABLED_METRICS_CONTENT = [
  "# HELP jaziggo_metrics_endpoint_enabled Metrics endpoint enabled state",
  "# TYPE jaziggo_metrics_endpoint_enabled gauge",
  "jaziggo_metrics_endpoint_enabled 0",
  "",
].join("\n")

export interface MetricsSnapshot {
  format: "prometheus"
  content: string
}

const locationSearchTotal =
  (register.getSingleMetric(
    LOCATION_SEARCH_TOTAL_NAME,
  ) as Counter<"result"> | undefined) ??
  new Counter<"result">({
    name: LOCATION_SEARCH_TOTAL_NAME,
    help: "Total location search operations by result",
    labelNames: ["result"],
  })

const locationSearchDuration =
  (register.getSingleMetric(
    LOCATION_SEARCH_DURATION_NAME,
  ) as Histogram | undefined) ??
  new Histogram({
    name: LOCATION_SEARCH_DURATION_NAME,
    help: "Location search operation duration in seconds",
    buckets: [0.05, 0.1, 0.25, 0.5, 1, 2, 3, 5, 10],
  })

const reportsGeneratedTotal =
  (register.getSingleMetric(
    REPORTS_GENERATED_TOTAL_NAME,
  ) as Counter<"type" | "result"> | undefined) ??
  new Counter<"type" | "result">({
    name: REPORTS_GENERATED_TOTAL_NAME,
    help: "Total administrative reports generated by type and result",
    labelNames: ["type", "result"],
  })

const reportGenerationDuration =
  (register.getSingleMetric(
    REPORT_GENERATION_DURATION_NAME,
  ) as Histogram<"type"> | undefined) ??
  new Histogram<"type">({
    name: REPORT_GENERATION_DURATION_NAME,
    help: "Administrative report generation duration in seconds",
    labelNames: ["type"],
    buckets: [0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 15, 30],
  })

function normalizeDuration(durationMs: number): number {
  if (!Number.isFinite(durationMs) || durationMs < 0) {
    return 0
  }

  return durationMs
}

function normalizeResultCount(
  resultCount: number | undefined,
): number | undefined {
  if (
    resultCount === undefined ||
    !Number.isSafeInteger(resultCount) ||
    resultCount < 0
  ) {
    return undefined
  }

  return resultCount
}

export function areMetricsEnabled(): boolean {
  return process.env.METRICS_ENABLED?.toLowerCase() === "true"
}

export async function collectMetricsSnapshot(): Promise<MetricsSnapshot> {
  if (!areMetricsEnabled()) {
    return {
      format: "prometheus",
      content: DISABLED_METRICS_CONTENT,
    }
  }

  const content = await register.metrics()

  return {
    format: "prometheus",
    content:
      content.trim().length > 0 ? content : DISABLED_METRICS_CONTENT,
  }
}

export function recordLocationSearchObservation(
  observation: LocationSearchObservation,
): void {
  const durationMs = normalizeDuration(observation.durationMs)
  const resultCount = normalizeResultCount(observation.resultCount)

  try {
    locationSearchTotal.inc({ result: observation.result })
    locationSearchDuration.observe(durationMs / 1000)
  } catch {
    // Observability must not change the location search outcome.
  }

  const record = {
    timestamp: new Date().toISOString(),
    level:
      observation.result === LOCATION_SEARCH_RESULT.ERROR
        ? "error"
        : observation.result === LOCATION_SEARCH_RESULT.EMPTY
          ? "warn"
          : "info",
    module: "location-search",
    operation: observation.operation,
    event: "location-search.completed",
    ...(observation.userId ? { userId: observation.userId } : {}),
    requestId: crypto.randomUUID(),
    message: "Location search completed",
    metadata: {
      result: observation.result,
      durationMs: Math.round(durationMs),
      ...(resultCount === undefined ? {} : { resultCount }),
    },
  }
  const serializedRecord = JSON.stringify(record)

  try {
    if (observation.result === LOCATION_SEARCH_RESULT.ERROR) {
      console.error(serializedRecord)
      return
    }

    if (observation.result === LOCATION_SEARCH_RESULT.EMPTY) {
      console.warn(serializedRecord)
      return
    }

    console.info(serializedRecord)
  } catch {
    // Observability must not change the location search outcome.
  }
}

export function recordReportObservation(
  observation: ReportObservation,
): void {
  const durationMs = normalizeDuration(observation.durationMs)
  const resultCount = normalizeResultCount(observation.resultCount)

  try {
    reportsGeneratedTotal.inc({
      type: observation.type,
      result: observation.result,
    })
    reportGenerationDuration.observe(
      { type: observation.type },
      durationMs / 1000,
    )
  } catch {
    // Observability must not change the report outcome.
  }

  const record = {
    timestamp: new Date().toISOString(),
    level:
      observation.result === REPORT_RESULT.ERROR
        ? "error"
        : observation.result === REPORT_RESULT.EMPTY
          ? "warn"
          : "info",
    module: "report",
    operation: "generate",
    event: "report.generated",
    ...(observation.userId ? { userId: observation.userId } : {}),
    requestId: crypto.randomUUID(),
    message: "Administrative report generation completed",
    metadata: {
      type: observation.type,
      result: observation.result,
      durationMs: Math.round(durationMs),
      ...(resultCount === undefined ? {} : { resultCount }),
    },
  }
  const serializedRecord = JSON.stringify(record)

  try {
    if (observation.result === REPORT_RESULT.ERROR) {
      console.error(serializedRecord)
      return
    }

    if (observation.result === REPORT_RESULT.EMPTY) {
      console.warn(serializedRecord)
      return
    }

    console.info(serializedRecord)
  } catch {
    // Observability must not change the report outcome.
  }
}
